package edu.amrita.amritacafe.menu

val DEFAULT_BREAKFAST_MENU: List<MenuItemUS> = listOf(
    MenuItemUS("Amara", "Amara", 65f, "Vegtables"),
    MenuItemUS("Sweet Corn", "Swe Corn", 70f, "Vegtables"),
    MenuItemUS("Red radish", "Red RAD", 75f, "Vegtables"),
    MenuItemUS("Broccoli", "Broccoli", 180f, "Vegtables"),
    MenuItemUS("green Zucchini", "GRE Zuc ", 180f, "Vegtables"),
    MenuItemUS("Yellow Zucchini", "YEL ZUC", 180f, "Vegtables"),
    MenuItemUS("Capsicum Red", "Cap RED", 170f, "Vegtables"),
    MenuItemUS("Capsicum Yellow", "Cap YEL ", 170f, "Vegtables"),
    MenuItemUS("Celery", "Celery", 170f, "Vegtables"),
    MenuItemUS("Red cabbage", "Red CAB", 80f, "Vegtables"),
    MenuItemUS("Mushrooms", "MUCH", 80f, "Vegtables"),
    MenuItemUS("Leeks", "Leeks", 150f, "Vegtables"),

    MenuItemUS("ഇഞ്ചി", "Ginger", 50f, "Vegtables"),
    MenuItemUS("ഏത്തക്കായ", "Raw Banana", 50f, "Vegtables"),
    MenuItemUS("തക്കാളി", " Tomato", 27f, "Vegtables"),
    MenuItemUS("കറിവേപ്പില", " Curry leaves", 63f, "Vegtables"),
    MenuItemUS("കാരറ്റ്", "Carrot", 80f, "Vegtables"),
    MenuItemUS("കിഴങ്ങ്", "Potato", 57f, "Vegtables"),
    MenuItemUS("കുക്കുമ്പർ", "Cucumber", 35f, "Vegtables"),
    MenuItemUS("നൈസ്", "Nice", 40f, "Vegtables"),
    MenuItemUS("കാബേജ്", "Cabbage", 45f, "Vegtables"),
    MenuItemUS("കോവക്കׯ ", "Kovakka", 45f, "Vegtables"),
    MenuItemUS("കൂർക്ക", "Koorkka", 67f, "Vegtables"),
    MenuItemUS("കാപ്സിക്കം", "Capsicum", 48f, "Vegtables"),
    MenuItemUS("കുമ്പളം", "White gourd", 28f, "Vegtables"),
    MenuItemUS("ചൗചൗ", "Chow chow", 30f, "Vegtables"),
    MenuItemUS("ചുരക്ക", "Bottle gourd", 32f, "Vegtables"),
    MenuItemUS("ചെറിയ ഉള്ളി", "Small onion", 90f, "Vegtables"),
    MenuItemUS("ചേന ", "Yam", 40f, "Vegtables"),
    MenuItemUS("പച്ച മുളക്", " Chili", 45f, "Vegtables"),
    MenuItemUS("പടവലം", "Snake gourd", 40f, "Vegtables"),
    MenuItemUS("പയർ ", "Long beans", 48f, "Vegtables"),
    MenuItemUS("പാവയ്ക്കാ", "Bitter gourd", 51f, "Vegtables"),
    MenuItemUS("കോലി ഫ്ലവർ", "Cauliflower", 50f, "Vegtables"),
    MenuItemUS("ബീൻസ്", "Beans", 53f, "Vegtables"),
    MenuItemUS("ബീറ്റ് രൂട്ട്", "Beetroot", 38f, "Vegtables"),
    MenuItemUS("മത്തങ്ങ", "Pumpkin", 31f, "Vegtables"),
    MenuItemUS("മല്ലിയില", "Coriander", 50f, "Vegtables"),
    MenuItemUS("മുള്ളങ്കി", "Radish", 32f, "Vegtables"),
    MenuItemUS("വഴുതന", "Brinjal", 38f, "Vegtables"),
    MenuItemUS("വെണ്ട", "Lady finger", 37f, "Vegtables"),
    MenuItemUS("വെള്ളരി", "Yellow cucumber", 30f, "Vegtables"),
    MenuItemUS("വെളുത്തുള്ളി", "Garlic", 113f, "Vegtables"),
    MenuItemUS("നാരങ്ങ", "Lemon", 51f, "Vegtables"),
    MenuItemUS("നെല്ലിക്കׯ ", "Amla", 55f, "Vegtables"),
    MenuItemUS("സവാള", " Savala", 68f, "Vegtables")
)

val DEFAULT_LUNCH_DINNER_MENU: List<MenuItemUS> = listOf(
    MenuItemUS("Sm Fries", "SMFF", 30f, "Fries"),
    MenuItemUS("Lg Fries", "LGFF", 60f, "Fries"),
    MenuItemUS("Sm Fries Salt", "SMSAFF", 35f, "Fries"),
    MenuItemUS("Lg Fries Salt", "LGSAFF", 70f, "Fries"),

    MenuItemUS("Grilled Cheese", "GC", 40f, "Fries"),
    MenuItemUS("Egg Cheese Sand", "ECS", 60f, "Fries"),
    MenuItemUS("Omelet Fries", "OMS", 50f, "Fries"),
    MenuItemUS("Deluxe Grill CH", "DXL GC", 75f, "Fries"),
    MenuItemUS("Grilled Ch FRT", "GC FRT", 45f, "Fries"),

    MenuItemUS("Simple Salad", "SAL", 30f, "Salad"),
    MenuItemUS("Sprout Salad", "SPRSAL", 50f, "Salad"),
    MenuItemUS("Deluxe Salad", "DXL SAL", 90f, "Salad"),
    MenuItemUS("Pesto Salad", "PSTO SAL", 80f, "Salad"),
    MenuItemUS("Quinoa Salad", "QNA SAL", 150f, "Salad"),

    MenuItemUS("Cheese Pizza", "CH PZA", 100f, "Pizza"),
    MenuItemUS("Olive Pizza", "OLV PZA", 135f, "Pizza"),
    MenuItemUS("Veg Pizza", "VEG PZA", 125f, "Pizza"),
    MenuItemUS("Vegan Veg Pizza", "VN VEG PZA", 100f, "Pizza"),
    MenuItemUS("Gourmet Pizza", "GM PZA", 150f, "Pizza"),
    MenuItemUS("Vegan Gourmet PZA", "VN GM PZA", 125f, "Pizza"),
    MenuItemUS("Pesto Pizza", "PSTO PZA", 125f, "Pizza"),
    MenuItemUS("Paneer Pizza", "PAN PZA", 150f, "Pizza"),
    MenuItemUS("Mediter. Pizza", "MED PZA", 125f, "Pizza"),

    MenuItemUS("Veggie Burger", "VB", 40f, "Burger"),
    MenuItemUS("Cheese Burger", "CB", 60f, "Burger"),
    MenuItemUS("Patty", "PATTY", 20f, "Burger"),
    MenuItemUS("Deluxe Burger", "DLXB", 80f, "Burger"),
    MenuItemUS("Pesto Burger", "PSTOB", 65f, "Burger"),

    MenuItemUS("Toast", "T", 3f, "Toast"),
    MenuItemUS("Butter Jam Toast", "BJT", 15f, "Toast"),
    MenuItemUS("Butter Toast", "BT", 10f, "Toast"),
    MenuItemUS("Jam Toast", "JT", 10f, "Toast"),
    MenuItemUS("Peanut But Toast", "PBT", 10f, "Toast"),
    MenuItemUS("Cheese Toast", "CHT", 25f, "Toast"),
    MenuItemUS("Honey Toast", "HT", 10f, "Toast"),
    MenuItemUS("Butter Honey Toast", "BHT", 20f, "Toast"),
    MenuItemUS("Choco Toast", "CHOC T", 15f, "Toast"),

    MenuItemUS("Kitcheri", "KITCH", 30f, "Kitcheri"),
    MenuItemUS("Steamed Veg", "ST VEG", 30f, "Kitcheri"),
    MenuItemUS("Quinoa", "QNA", 100f, "Kitcheri"),
    MenuItemUS("Steamed Broccoli", "ST BROC", 100f, "Kitcheri"),
    MenuItemUS("Hummus", "HUM", 30f, "Kitcheri"),

    MenuItemUS("Plain Pasta", "PL PSTA", 30f, "Pasta"),
    MenuItemUS("Pasta Tomato Sauce", "PSTA TOM", 60f, "Pasta"),
    MenuItemUS("Pasta Tomato Cheese", "PAST TOM CH", 80f, "Pasta"),
    MenuItemUS("Pasta All Soy", "PAST ALL SOY", 90f, "Pasta"),
    MenuItemUS("Pesto Pasta", "PSTO PAST", 60f, "Pasta"),
    MenuItemUS("Vegan Gourmet Pasta", "VN GM PAST", 100f, "Pasta"),
    MenuItemUS("Deluxe Pasta", "DLX PAST", 115f, "Pasta"),

    MenuItemUS("Egg Sunny Side Up", "FE SSU", 20f, "Eggs"),
    MenuItemUS("Fried Egg Overhard", "FE OH", 20f, "Eggs"),
    MenuItemUS("Plain Omelet", "OM", 40f, "Eggs"),
    MenuItemUS("Veggie Omelet", "VEG OM", 60f, "Eggs"),
    MenuItemUS("Deluxe Omelet", "DXL OM", 115f, "Eggs"),
    MenuItemUS("Cheese Omelet", "OM CH", 60f, "Eggs"),
    MenuItemUS("Fresh Tomato Omelet", "OM FRT", 45f, "Eggs"),
    MenuItemUS("Pesto Omelet", "PSTO OM", 70f, "Eggs"),
    MenuItemUS("Olive Omelet", "OLV OM", 75f, "Eggs"),
    MenuItemUS("Veggie Cheese Omelet", "VEG CH OM", 80f, "Eggs"),
    MenuItemUS("Gourmet Omelet", "GM OM", 110f, "Eggs"),
    MenuItemUS("Onion Omelet", "ON OM", 45f, "Eggs"),

    MenuItemUS("Bread", "BREAD", 3f, "Side"),
    MenuItemUS("Butter", "BUTT", 10f, "Side"),
    MenuItemUS("Capsicum", "CAP", 10f, "Side"),
    MenuItemUS("Carrot", "CARROT", 10f, "Side"),
    MenuItemUS("Honey", "HON", 10f, "Side"),
    MenuItemUS("Jam", "JAM", 10f, "Side"),
    MenuItemUS("Sliced Cheese", "SL CH", 20f, "Side"),
    MenuItemUS("Mustard", "MRD", 10f, "Side"),
    MenuItemUS("Choco Spread", "CHOC", 15f, "Side"),
    MenuItemUS("Peanut Butter", "PB", 10f, "Side"),
    MenuItemUS("Patty", "PATTY", 20f, "Side"),
    MenuItemUS("Cucumber", "CUKE", 10f, "Side"),
    MenuItemUS("Pesto", "PSTO", 25f, "Side"),
    MenuItemUS("Raw Egg", "RAW EGG", 10f, "Side"),
    MenuItemUS("Gomasio", "GOMAZ", 10f, "Side"),
    MenuItemUS("Ketchup", "KETUP", 5f, "Side"),
    MenuItemUS("Olive", "OLV", 30f, "Side"),
    MenuItemUS("Onion", "ON", 5f, "Side"),
    MenuItemUS("Pickle", "PKL", 10f, "Side"),
    MenuItemUS("Dressing", "DRS", 10f, "Side"),
    MenuItemUS("Soya", "SOYA", 10f, "Side"),
    MenuItemUS("Sprouts", "SPRTS", 10f, "Side"),
    MenuItemUS("Fresh Tomato", "FRT", 5f, "Side"),
    MenuItemUS("Tomato Sauce", "TOM", 10f, "Side"),
    MenuItemUS("Bun", "BUN", 10f, "Side"),
    MenuItemUS("Grated Cheese", "CH", 20f, "Side"),
    MenuItemUS("Mayo", "MAYO", 10f, "Side")
)