package edu.amrita.amritacafe.menu

val DEFAULT_BREAKFAST_MENU: List<MenuItemUS> = listOf(
    MenuItemUS("Amara", "Amara", 65f, "Vegtables"),
    MenuItemUS("Beetroot", "Beetroot", 38f, "Vegtables"),
    MenuItemUS("Beans", "Beans", 53f, "Vegtables"),
    MenuItemUS("Bitter gourd", "Bitter gourd", 51f, "Vegtables"),
    MenuItemUS("Bottle gourd", "Bottle gourd", 32f, "Vegtables"),
    MenuItemUS("Brinjal", "Brinjal", 38f, "Vegtables"),
    MenuItemUS("Broccoli", "Broccoli", 180f, "Vegtables"),
    MenuItemUS("Cabbage", "Cabbage", 45f, "Vegtables"),
    MenuItemUS("Capsicum", "Capsicum", 48f, "Vegtables"),
    MenuItemUS("Capsicum Red", "Cap RED", 170f, "Vegtables"),
    MenuItemUS("Capsicum Yellow", "Cap YEL ", 170f, "Vegtables"),
    MenuItemUS("Carrot", "Carrot", 80f, "Vegtables"),
    MenuItemUS("Cauliflower", "Cauliflower", 50f, "Vegtables"),
    MenuItemUS("Celery", "Celery", 170f, "Vegtables"),
    MenuItemUS("Chembu", "Chembu", 10f, "Vegtables"),
    MenuItemUS("Chili", "Chili", 45f, "Vegtables"),
    MenuItemUS("Chow chow", "Chow chow", 30f, "Vegtables"),
    MenuItemUS("Coriander", "Coriander", 50f, "Vegtables"),
    MenuItemUS("Cucumber", "Cucumber", 35f, "Vegtables"),
    MenuItemUS("Curry leaves", "Curry leaves", 63f, "Vegtables"),
    MenuItemUS("Garlic", "Garlic", 113f, "Vegtables"),
    MenuItemUS("Ginger", "Ginger", 50f, "Vegtables"),
    MenuItemUS("Green peas", "Green peas", 10f, "Vegtables"),
    MenuItemUS("Green Zucchini", "GRE Zuc ", 180f, "Vegtables"),
    MenuItemUS("Kappa", "Kappa", 10f, "Vegtables"),
    MenuItemUS("Koorkka", "Koorkka", 67f, "Vegtables"),
    MenuItemUS("Kovakka", "Kovakka", 45f, "Vegtables"),
    MenuItemUS("Lady finger", "Lady finger", 37f, "Vegtables"),
    MenuItemUS("Leakes", "Leakes", 150f, "Vegtables"),
    MenuItemUS("Lemon", "Lemon", 51f, "Vegtables"),
    MenuItemUS("Lettuce", "Lettuce", 10f, "Vegtables"),
    MenuItemUS("Long beans", "Long beans", 48f, "Vegtables"),
    MenuItemUS("Mango", "Mango", 10f, "Vegtables"),
    MenuItemUS("Mushroom", "Mushroom", 80f, "Vegtables"),
    MenuItemUS("Muringakka", "Muringakka", 10f, "Vegtables"),
    MenuItemUS("Mushrooms", "MUCH", 80f, "Vegtables"),
    MenuItemUS("Nice", "Nice", 40f, "Vegtables"),
    MenuItemUS("Palak", "Palak", 10f, "Vegtables"),
    MenuItemUS("Potato", "Potato", 57f, "Vegtables"),
    MenuItemUS("Pumpkin", "Pumpkin", 31f, "Vegtables"),
    MenuItemUS("Radish", "Radish", 32f, "Vegtables"),
    MenuItemUS("Raw Banana", "Raw Banana", 50f, "Vegtables"),
    MenuItemUS("Red cabbage", "Red CAB", 80f, "Vegtables"),
    MenuItemUS("Red radish", "Red RAD", 75f, "Vegtables"),
    MenuItemUS("Savala", "Savala", 68f, "Vegtables"),
    MenuItemUS("Small onion", "Small onion", 90f, "Vegtables"),
    MenuItemUS("Snake gourd", "Snake gourd", 40f, "Vegtables"),
    MenuItemUS("Spring onion", "Spring onion", 10f, "Vegtables"),
    MenuItemUS("Swe Corn", "Swe Corn", 70f, "Vegtables"),
    MenuItemUS("Sweet Corn", "Sweet Corn", 10f, "Vegtables"),
    MenuItemUS("Sweet potato", "Sweet potato", 10f, "Vegtables"),
    MenuItemUS("Tomato", "Tomato", 27f, "Vegtables"),
    MenuItemUS("White eggs", "White eggs", 10f, "Vegtables"),
    MenuItemUS("White gourd", "White gourd", 28f, "Vegtables"),
    MenuItemUS("Yam", "Yam", 40f, "Vegtables"),
    MenuItemUS("Yellow cucumber", "Yellow cucumber", 30f, "Vegtables"),
    MenuItemUS("Yellow Zucchini", "YEL ZUC", 180f, "Vegtables"),
    MenuItemUS("Zucchini", "Zucchini", 10f, "Vegtables"),
)